"""spec update

Revision ID: 5ddb5bb9f504
Revises: 736652b46c65
Create Date: 2025-09-19 06:18:46.635997

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '5ddb5bb9f504'
down_revision = '736652b46c65'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
