"""spec update

Revision ID: 6631e3ac05fa
Revises: None
Create Date: 2025-09-16 01:48:45.464826

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '6631e3ac05fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
