"""spec update

Revision ID: 736652b46c65
Revises: 8a1f12376bcd
Create Date: 2025-09-16 04:04:14.453083

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '736652b46c65'
down_revision = '8a1f12376bcd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
