"""spec update

Revision ID: 8a1f12376bcd
Revises: 6631e3ac05fa
Create Date: 2025-09-16 04:02:07.546888

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8a1f12376bcd'
down_revision = '6631e3ac05fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
